import type { Metadata } from 'next';
import { ToastContainer } from 'react-toastify';
import { AuthContextProvider } from './context/AuthContext';
import 'bootstrap/dist/css/bootstrap.css';
import 'bootstrap-icons/font/bootstrap-icons.css';
import './globals.css';
import NavBar from './components/UI/Navbar/Navbar';

export const metadata: Metadata = {
	title: 'Sport Booking',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			{/*
        <head /> will contain the components returned by the nearest parent
        head.js. Find out more at https://beta.nextjs.org/docs/api-reference/file-conventions/head
      */}
			<head />
			<body>
				<ToastContainer />
				<AuthContextProvider>
					<NavBar />
					{children}
				</AuthContextProvider>
			</body>
		</html>
	);
}
