import type { Metadata } from 'next';
import { ToastContainer } from 'react-toastify';
import { SpeedInsights } from '@vercel/speed-insights/next';
import { AuthContextProvider } from './context/AuthContext';
import './globals.css';
import NavBar from './components/UI/Navbar/Navbar';
import BootstrapClient from './components/BootstrapClient';

export const metadata: Metadata = {
	title: 'Sport Booking',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			{/*
        <head /> will contain the components returned by the nearest parent
        head.js. Find out more at https://beta.nextjs.org/docs/api-reference/file-conventions/head
		<head />
	  */}
			<body>
				<BootstrapClient />
				<ToastContainer />
				<AuthContextProvider>
					<NavBar />
					{children}
				</AuthContextProvider>
				<SpeedInsights />
			</body>
		</html>
	);
}
